<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 3 </p>

Group Name: Group 8

In [1]:
import numpy as np

In [2]:
#Printing 2D Array/Matrix
A = np.array([[5,2,3], [6,1,3],[2,4,1]])
print(A)

[[5 2 3]
 [6 1 3]
 [2 4 1]]


In [3]:
#Slicing the Matrix-A to get desired output as B as mentioned in instructions
B = A[0:2,0:2] 
print("B = ",B)

B =  [[5 2]
 [6 1]]


In [4]:
#Slicing the Matrix-A to get desired output as C as mentioned in instructions
C = A[1:,1:] 
print("C = ",C)

C =  [[1 3]
 [4 1]]
